name: deployment
run-name: Deploying Image Uploader
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.10
        uses: actions/setup-node@v3
        with:
          node-version: '16.10.0'
      - name: Install yarn and run unittest
        run: |
          cd client
          yarn
          yarn test
        env:
          CI: true