name: deployment
run-name: Deploying Image Uploader
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.10
        uses: actions/setup-node@v3
        with:
          node-version: '16.10.0'
      - name: Install yarn
        run: |
          cd client
          yarn
        env:
          CI: true
      - name: Docker Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run:
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Docker Push
        env:
          REPO: image-uploader-client
        run: |
          cd client
          docker build -t $REPO .
          docker tag $REPO:latest ${{secrets.DOCKER_USER}}/$REPO:latest
          docker push ${{secrets.DOCKER_USER}}/$REPO
      - name: Docker Pull and Run from Hub
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
            docker pull ${{secrets.DOCKER_USER}}/$REPO:latest
            docker stop image-uploader-client
            docker rm image-uploader-client
            docker run -d --name image-uploader-client -e REACT_APP_API_URL='http://cachetitodev.xyz:3001' -p 81:80 ${{secrets.DOCKER_USER}}/$REPO:latest
