name: deploy-client
run-name: Deploying Image Uploader Client
on:
  push:
    tags:
      - '*'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.10
        uses: actions/setup-node@v3
        with:
          node-version: '16.10.0'
      - name: Install yarn
        run: |
          cd client
          yarn
        env:
          CI: true
      - name: Docker Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run:
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Docker Push
        env:
          REPO: image-uploader-client
        run: |
          cd client
          docker build -t ${{secrets.DOCKER_USER}}/$REPO:${{github.ref_name}} .
          docker push ${{secrets.DOCKER_USER}}/$REPO:${{github.ref_name}}
      - name: Docker Pull and Run from Hub
        uses: appleboy/ssh-action@v0.1.10
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          DOCKER_IMAGE: ${{secrets.DOCKER_USER}}/image-uploader-client:${{github.ref_name}}
          REACT_APP_API_URL: ${{secrets.REACT_APP_API_URL}}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          envs: DOCKER_USER,DOCKER_PASSWORD,DOCKER_IMAGE,REACT_APP_API_URL
          script: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker pull $DOCKER_IMAGE
            docker stop image-uploader-client
            docker rm image-uploader-client
            docker run -d --name image-uploader-client -e REACT_APP_API_URL=$REACT_APP_API_URL -p 81:80 $DOCKER_IMAGE
